export const quizQuestions = [
    // Questions obligatoires
    {
        slug: "poids-minimum",
        text: "Pesez-vous au moins 50 kg ?",
        goodAnswer: "oui",
        mandatory: true,
        reason: "Un poids minimum de 50 kg est requis pour donner en toute sécurité.",
    },
    {
        slug: "test-positif-ist",
        text: "Avez-vous déjà été testé.e positif.ve au VIH, à l’hépatite B, à l’hépatite C ou à la syphilis ?",
        goodAnswer: "non",
        mandatory: true,
        reason: "Un test positif à l’une de ces infections empêche le don du sang.",
    },
    {
        slug: "antecedent-cancer",
        text: "Avez-vous déjà eu un cancer au cours de votre vie ?",
        goodAnswer: "non",
        mandatory: true,
        reason: "Certains antécédents de cancer ne permettent pas le don du sang.",
    },
    {
        slug: "hemochromatose",
        text: "Êtes-vous porteur.se d’une hémochromatose génétique ?",
        goodAnswer: "non",
        mandatory: true,
        reason: "L’hémochromatose génétique demande un suivi spécifique et empêche le don classique.",
    },
    {
        slug: "maladie-cardiaque",
        text: "Souffrez-vous d’une maladie cardiaque ou avez-vous déjà fait un infarctus ?",
        goodAnswer: "non",
        mandatory: true,
        reason: "Une maladie cardiaque connue ne permet pas le don du sang.",
    },
    {
        slug: "diabete-insuline",
        text: "Êtes-vous diabétique et traité.e par insuline ?",
        goodAnswer: "non",
        mandatory: true,
        reason: "Le diabète traité par insuline est une contre-indication au don.",
    },
    {
        slug: "transfusion-recue",
        text: "Avez-vous déjà reçu une transfusion de sang ?",
        goodAnswer: "non",
        mandatory: true,
        reason: "Avoir reçu une transfusion empêche le don du sang par précaution.",
    },
    {
        slug: "drogues-injectables",
        text: "Avez-vous déjà consommé des drogues par injection ?",
        goodAnswer: "non",
        mandatory: true,
        reason: "La consommation de drogues injectables empêche le don du sang.",
    },

    // Questions optionnelles
    {
        slug: "partenaires-recents",
        text: "Au cours des 4 derniers mois, avez-vous eu un nouveau partenaire sexuel ou plusieurs partenaires sexuels ?",
        goodAnswer: "non",
        mandatory: false,
        reason: "Un délai de 4 mois est conseillé après un changement de partenaire.",
    },
    {
        slug: "tatouage-piercing",
        text: "Vous êtes-vous fait tatouer ou percer au cours des 4 derniers mois ?",
        goodAnswer: "non",
        mandatory: false,
        reason: "Après un tatouage ou un piercing, un délai de 4 mois est conseillé.",
    },
    {
        slug: "gastro-coloscopie",
        text: "Avez-vous subi une gastroscopie ou une coloscopie au cours des 4 derniers mois ?",
        goodAnswer: "non",
        mandatory: false,
        reason: "Après une endoscopie récente, un délai de 4 mois est recommandé.",
    },
    {
        slug: "voyage-hors-europe",
        text: "Avez-vous voyagé hors d’Europe au cours des 4 derniers mois ?",
        goodAnswer: "non",
        mandatory: false,
        reason: "Certaines destinations demandent un délai d’attente avant le don.",
    },
    {
        slug: "antibiotiques",
        text: "Avez-vous pris des antibiotiques au cours des 7 derniers jours ?",
        goodAnswer: "non",
        mandatory: false,
        reason: "Mieux vaut attendre la fin d’un traitement antibiotique avant de donner.",
    },
    {
        slug: "grossesse-recente",
        text: "Avez-vous accouché au cours des 6 derniers mois ?",
        goodAnswer: "non",
        mandatory: false,
        reason: "Un délai de 6 mois après un accouchement est conseillé avant le don.",
    },
    {
        slug: "chirurgie-recente",
        text: "Avez-vous subi une intervention chirurgicale au cours des 4 derniers mois ?",
        goodAnswer: "non",
        mandatory: false,
        reason: "Après une opération, un délai de récupération est recommandé.",
    },
    {
        slug: "vaccin-recent",
        text: "Avez-vous été vacciné.e au cours des 4 dernières semaines ?",
        goodAnswer: "non",
        mandatory: false,
        reason: "Selon le vaccin, un court délai d’attente peut être conseillé.",
    },
    {
        slug: "fievre-infection",
        text: "Avez-vous eu de la fièvre ou une infection au cours des 2 dernières semaines ?",
        goodAnswer: "non",
        mandatory: false,
        reason: "Mieux vaut être totalement rétabli.e avant de donner son sang.",
    },
    {
        slug: "bonne-sante",
        text: "Vous sentez-vous en bonne santé aujourd’hui ?",
        goodAnswer: "oui",
        mandatory: false,
        reason: "Mieux vaut être en pleine forme le jour du don pour vous et le receveur.",
    },
];
